repos:
  # Ruff - Fast Python linter and formatter (replaces black, isort, flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Security scanning
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/]
        exclude: tests/

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements

  # Type checking (optional - can be enabled if needed)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]
  #       additional_dependencies: [types-requests]

  # Local pipx installation test
  - repo: local
    hooks:
      - id: pipx-installation-test
        name: pipx installation test
        entry: python -m pytest tests/test_pipx_installation.py::TestPackageStructure -v
        language: system
        pass_filenames: false
        stages: [pre-push]
